"""add_team_elo_ratings_table_for_M1

Revision ID: ae0ea4ea9892
Revises: d7d93b3ec71e
Create Date: 2026-06-13 12:21:05.469976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0ea4ea9892'
down_revision: Union[str, None] = 'd7d93b3ec71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_elo_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_elo_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_elo_ratings_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_elo_ratings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_elo_ratings_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_elo_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_elo_ratings_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_elo_ratings_id'))
        batch_op.drop_index(batch_op.f('ix_team_elo_ratings_as_of_date'))

    op.drop_table('team_elo_ratings')
    # ### end Alembic commands ###
